// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3yk2RiUKPpaRFt45e7R1cb6yRolH332U',
    appId: '1:139242835792:web:84bcef46d3513219e92655',
    messagingSenderId: '139242835792',
    projectId: 'law-firm-app-4d76a',
    authDomain: 'law-firm-app-4d76a.firebaseapp.com',
    storageBucket: 'law-firm-app-4d76a.appspot.com',
    measurementId: 'G-ENB6B2PB9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4FhtrzrW8EI5XL9RDxyNrHsIZb_LTiQs',
    appId: '1:139242835792:android:0db3da68d104ae22e92655',
    messagingSenderId: '139242835792',
    projectId: 'law-firm-app-4d76a',
    storageBucket: 'law-firm-app-4d76a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8DoYBYc5hNnl2K30621JwdlM3-XA73l0',
    appId: '1:139242835792:ios:febdc70b35f92f5ae92655',
    messagingSenderId: '139242835792',
    projectId: 'law-firm-app-4d76a',
    storageBucket: 'law-firm-app-4d76a.appspot.com',
    iosBundleId: 'com.example.caseManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8DoYBYc5hNnl2K30621JwdlM3-XA73l0',
    appId: '1:139242835792:ios:a850b10c28b9eccfe92655',
    messagingSenderId: '139242835792',
    projectId: 'law-firm-app-4d76a',
    storageBucket: 'law-firm-app-4d76a.appspot.com',
    iosBundleId: 'com.example.caseManagement.RunnerTests',
  );
}
